---
title: "Project Proposal"
output: html_document
authors: Ashley Anderson, Cameron Stocker, Hexiang Zhang, & Tyler Kruzan
---

#### Team Members:

Project Coordinator: Ashley Anderson

Cameron Stocker, Hexiang Zhang, & Tyler Kruzan

#### Dataset Link

Link to Dataset can be found on Kaggle or through this link: https://www.kaggle.com/PromptCloudHQ/imdb-data

#### Dataset Overview

```{r}

# Load dataset
movie = read.csv("IMDB-Movie-Data.csv")

str(movie)
summary(movie)
head(movie)

```

#### Background

This data set that came from IMDb, includes data about the 1,000 most popular movies that came out from 2006 - 2016. Useful variables include Title, Director, Year, Runtime, Rating, Metascore, & Revenue. There are some dirtier variables like Description, Actors, & Genre that contain lengthy character strings that will need to be parsed and cleaned or simply omitted from the data we use.

IMDb, which stands for Internet Movie Database, is an online source for data associated with films, TV shows, video games, and other streamable content. For each title, users can find information relating to the starring cast, producers, and plot summaries, as well as both critic and fan reviews. As of May 2019, IMDb had 83 million registered users and approximately 6 million titles, including 516,726 feature films. IMDb ratings are based on user ratings on a scale from 1 to 10. The raw ratings are then filtered and weighted, creating a weighted mean rating for each film. The formula for calculating the weighted rating is $W = \frac{R*v + C*m}{v+m}$, where $R$ is the raw average, $v$ is the number of votes, $m$ is the minimum votes required to be included in the Top 250 (which is currently 25,000), and $C$ is the mean vote for the reports (which is currently 7.0).

| Dataset's Columns  | Description      |
| ------------------ | ---------------- |
| Rank               | Movie Rank Order |
| Title              | Tite of the film |
| Genre              | Comma separated-list of genres used to classify the film |
| Description        | Brief one-sentence movie summary |
| Director           | The name of the film's director |
| Actors             | A comma-separated list of the main stars of the film |
| Year               | The year that the film released as an integer. |
| Runtime (Minutes)  | The duration of the film in minutes.|
| Rating             | User rating for the movie 0-10 |
| Votes              | Number of votes |
| Revenue (Millions) | Movie revenue in millions |
| Metascore          | An aggregated average of critic scores. Values are between 0 and 100. Higher scores represent positive reviews. |

#### Exploratory Analysis

For analysis, we will be able to examine a variety of questions. First we plan to find which actors and directors are most commonly involved with successful movies. We can define success by looking at a movie's rating or its revenue. We will extract using the separate method and clean the 'Actors' column into multiple rows. From there we can find the average movie rating and revenue on an actor specific basis.

We will also dive into what factors are correlated with a higher rating/revenue. We will examine the genre, runtime, and votes variables to see if they have any significance in predicting rating and revenue. This can be done through ploting the dataset. 

We will examine relationships between different factors in a movie over time such as the year it was made and movie performances like runtime, votes, rating, and revenue to see how the components of top movies have changed over the years. This can also be done through plotting the dataset. 

We will also explore the possibility of merging multiple datasets to add in a columns like stating a movie's budget. This can be done through using the join methods. Joined information could help explain a movie's rating/revenue. 